<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCore.Design\EFCore.Design.csproj" />
    <ProjectReference Include="..\EFCore.SqlServer\EFCore.SqlServer.csproj" />
  </ItemGroup>

</Project>
